DROP TABLE TBL_USER CASCADE CONSTRAINTS;
DROP TABLE TBL_CHARGING_STATION CASCADE CONSTRAINTS;
DROP TABLE TBL_GAS_STATION CASCADE CONSTRAINTS;
DROP TABLE TBL_FAVORITE CASCADE CONSTRAINTS;

CREATE TABLE TBL_USER (
   USER_ID   VARCHAR2(200)    NULL,
   USER_PW   VARCHAR2(200)   NOT NULL,
   USER_NAME   VARCHAR2(200)   NOT NULL,
   USER_PHONE   VARCHAR2(200)   NOT NULL,
   USER_EMAIL   VARCHAR2(200)   NOT NULL,
   USER_POWER_TYPE   VARCHAR2(200)   CHECK(USER_POWER_TYPE IN ('G', 'C')) NULL
--    CONSTRAINT PK_USER_ID PRIMARY KEY (USER_ID)
);

CREATE TABLE TBL_CHARGING_STATION (
    C_REGION_CODE       NUMBER         NOT NULL,
    C_STATION_ADDRESS VARCHAR2(200)  NULL,
    C_ADDRDETAIL      VARCHAR2(200)  NULL,
    C_STATION_NAME    VARCHAR2(200)   NULL,
    C_STATION_ID      VARCHAR2(200)   NOT NULL,  
    C_TIME            VARCHAR2(200)   NULL,
    CHARGER_TYPE      NUMBER         NULL,
    C_PARKINGFEE      VARCHAR2(200)   NULL,
    C_MANAGEMENT      VARCHAR2(200)   NULL,
    C_STATION_TEL     VARCHAR2(200)   NULL,
    C_GUIDE           VARCHAR2(200)   NULL,
    CHARGING_CAPA     NUMBER         NULL,
    CHARGING_METHOD   VARCHAR2(200)   NULL
--    CONSTRAINT PK_C_STATION_ID PRIMARY KEY(C_STATION_ID)
);


CREATE TABLE TBL_GAS_STATION (
    G_STATION_ID VARCHAR2(200)   NOT NULL,
   G_STATION_TRADEMARK   VARCHAR2(200)   NULL,
   G_STATION_NAME   VARCHAR2(200)   NOT NULL,
   G_STATION_ADDRESS   VARCHAR2(200)   NOT NULL,
   G_STATION_TEL   VARCHAR2(200)   NOT NULL,
   G_REGION_CODE   NUMBER       NOT NULL,
   MAINT_YN   VARCHAR2(200)   NULL,
   WASH_YN   VARCHAR2(200)   NULL,
   CVS_YN   VARCHAR2(200)   NULL,
   GASOLINE_PRICE   NUMBER       NOT NULL,
   DIESEL_PRICE   NUMBER       NOT NULL
--    CONSTRAINT PK_G_STATION_ID PRIMARY KEY (G_STATION_ID)
);

CREATE TABLE TBL_FAVORITE (
   STATION_ID   VARCHAR2(200)   NULL,
   STATION_NAME   VARCHAR2(200)   NULL,
   USER_ID   VARCHAR2(200)   NULL
--    CONSTRAINT PK_G_BOOKMARK_NO PRIMARY KEY (BOOKMARK_NO),
--    CONSTRAINT FK_G_USER_ID FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID),
--    CONSTRAINT FK_G_STATION_ID FOREIGN KEY(G_STATION_ID) REFERENCES TBL_GAS_STATION(G_STATION_ID)
);

COMMIT; 